/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRelaxaRouteImport } from './routes/_authenticated/relaxa'
import { Route as AuthenticatedMyProfilesRouteImport } from './routes/_authenticated/my-profiles'
import { Route as AuthenticatedAtvesterRouteImport } from './routes/_authenticated/atvester'
import { Route as AuthenticatedAddFundsRouteImport } from './routes/_authenticated/add-funds'
import { Route as AuthenticatedMModuleRouteImport } from './routes/_authenticated/m.$module'
import { Route as AuthenticatedMModuleIndexRouteImport } from './routes/_authenticated/m.$module.index'
import { Route as AuthenticatedMModuleCategoryRouteImport } from './routes/_authenticated/m.$module.$category'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelaxaRoute = AuthenticatedRelaxaRouteImport.update({
  id: '/relaxa',
  path: '/relaxa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyProfilesRoute = AuthenticatedMyProfilesRouteImport.update({
  id: '/my-profiles',
  path: '/my-profiles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAtvesterRoute = AuthenticatedAtvesterRouteImport.update({
  id: '/atvester',
  path: '/atvester',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAddFundsRoute = AuthenticatedAddFundsRouteImport.update({
  id: '/add-funds',
  path: '/add-funds',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMModuleRoute = AuthenticatedMModuleRouteImport.update({
  id: '/m/$module',
  path: '/m/$module',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMModuleIndexRoute =
  AuthenticatedMModuleIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMModuleRoute,
  } as any)
const AuthenticatedMModuleCategoryRoute =
  AuthenticatedMModuleCategoryRouteImport.update({
    id: '/$category',
    path: '/$category',
    getParentRoute: () => AuthenticatedMModuleRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/add-funds': typeof AuthenticatedAddFundsRoute
  '/atvester': typeof AuthenticatedAtvesterRoute
  '/my-profiles': typeof AuthenticatedMyProfilesRoute
  '/relaxa': typeof AuthenticatedRelaxaRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/m/$module': typeof AuthenticatedMModuleRouteWithChildren
  '/m/$module/$category': typeof AuthenticatedMModuleCategoryRoute
  '/m/$module/': typeof AuthenticatedMModuleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/add-funds': typeof AuthenticatedAddFundsRoute
  '/atvester': typeof AuthenticatedAtvesterRoute
  '/my-profiles': typeof AuthenticatedMyProfilesRoute
  '/relaxa': typeof AuthenticatedRelaxaRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/m/$module/$category': typeof AuthenticatedMModuleCategoryRoute
  '/m/$module': typeof AuthenticatedMModuleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/add-funds': typeof AuthenticatedAddFundsRoute
  '/_authenticated/atvester': typeof AuthenticatedAtvesterRoute
  '/_authenticated/my-profiles': typeof AuthenticatedMyProfilesRoute
  '/_authenticated/relaxa': typeof AuthenticatedRelaxaRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/m/$module': typeof AuthenticatedMModuleRouteWithChildren
  '/_authenticated/m/$module/$category': typeof AuthenticatedMModuleCategoryRoute
  '/_authenticated/m/$module/': typeof AuthenticatedMModuleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/add-funds'
    | '/atvester'
    | '/my-profiles'
    | '/relaxa'
    | '/settings'
    | '/support'
    | '/m/$module'
    | '/m/$module/$category'
    | '/m/$module/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/add-funds'
    | '/atvester'
    | '/my-profiles'
    | '/relaxa'
    | '/settings'
    | '/support'
    | '/m/$module/$category'
    | '/m/$module'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/add-funds'
    | '/_authenticated/atvester'
    | '/_authenticated/my-profiles'
    | '/_authenticated/relaxa'
    | '/_authenticated/settings'
    | '/_authenticated/support'
    | '/_authenticated/m/$module'
    | '/_authenticated/m/$module/$category'
    | '/_authenticated/m/$module/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relaxa': {
      id: '/_authenticated/relaxa'
      path: '/relaxa'
      fullPath: '/relaxa'
      preLoaderRoute: typeof AuthenticatedRelaxaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-profiles': {
      id: '/_authenticated/my-profiles'
      path: '/my-profiles'
      fullPath: '/my-profiles'
      preLoaderRoute: typeof AuthenticatedMyProfilesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atvester': {
      id: '/_authenticated/atvester'
      path: '/atvester'
      fullPath: '/atvester'
      preLoaderRoute: typeof AuthenticatedAtvesterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/add-funds': {
      id: '/_authenticated/add-funds'
      path: '/add-funds'
      fullPath: '/add-funds'
      preLoaderRoute: typeof AuthenticatedAddFundsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/m/$module': {
      id: '/_authenticated/m/$module'
      path: '/m/$module'
      fullPath: '/m/$module'
      preLoaderRoute: typeof AuthenticatedMModuleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/m/$module/': {
      id: '/_authenticated/m/$module/'
      path: '/'
      fullPath: '/m/$module/'
      preLoaderRoute: typeof AuthenticatedMModuleIndexRouteImport
      parentRoute: typeof AuthenticatedMModuleRoute
    }
    '/_authenticated/m/$module/$category': {
      id: '/_authenticated/m/$module/$category'
      path: '/$category'
      fullPath: '/m/$module/$category'
      preLoaderRoute: typeof AuthenticatedMModuleCategoryRouteImport
      parentRoute: typeof AuthenticatedMModuleRoute
    }
  }
}

interface AuthenticatedMModuleRouteChildren {
  AuthenticatedMModuleCategoryRoute: typeof AuthenticatedMModuleCategoryRoute
  AuthenticatedMModuleIndexRoute: typeof AuthenticatedMModuleIndexRoute
}

const AuthenticatedMModuleRouteChildren: AuthenticatedMModuleRouteChildren = {
  AuthenticatedMModuleCategoryRoute: AuthenticatedMModuleCategoryRoute,
  AuthenticatedMModuleIndexRoute: AuthenticatedMModuleIndexRoute,
}

const AuthenticatedMModuleRouteWithChildren =
  AuthenticatedMModuleRoute._addFileChildren(AuthenticatedMModuleRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAddFundsRoute: typeof AuthenticatedAddFundsRoute
  AuthenticatedAtvesterRoute: typeof AuthenticatedAtvesterRoute
  AuthenticatedMyProfilesRoute: typeof AuthenticatedMyProfilesRoute
  AuthenticatedRelaxaRoute: typeof AuthenticatedRelaxaRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedMModuleRoute: typeof AuthenticatedMModuleRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAddFundsRoute: AuthenticatedAddFundsRoute,
  AuthenticatedAtvesterRoute: AuthenticatedAtvesterRoute,
  AuthenticatedMyProfilesRoute: AuthenticatedMyProfilesRoute,
  AuthenticatedRelaxaRoute: AuthenticatedRelaxaRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedMModuleRoute: AuthenticatedMModuleRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
